<a href="https://colab.research.google.com/github/kgs12110/dap__/blob/main/bundesliga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

## **분데스리가 20-21 시즌 상위 7팀 선수 스탯**
(이름 / 클럽 / 국적 / 포지션 / 나이 / 출전 경기 / 선발 / 출전 시간 (분) / 골 / 도움 / 패스 시도 / 패스 성공률 / PK / PK 시도 / xG / xA / 경고 / 퇴장)

총 188명

데이터 출처 : (https://www.kaggle.com/rajatrc1705/bundesliga-top-7-teams-offensive-stats/version/2?select=bundesliga_top7_v2.csv)

In [ ]:
df = pd.read_csv('bundesliga_top7_v2.csv')
df

                   Name           Club  ... Yellow_Cards Red_Cards
0          Manuel Neuer  Bayern Munich  ...            1         0
1         Thomas Müller  Bayern Munich  ...            0         0
2           David Alaba  Bayern Munich  ...            4         0
3        Jérôme Boateng  Bayern Munich  ...            6         0
4    Robert Lewandowski  Bayern Munich  ...            4         0
..                  ...            ...  ...          ...       ...
183        Loris Karius   Union Berlin  ...            0         0
184         Akaki Gogia   Union Berlin  ...            1         0
185         Leon Dajaku   Union Berlin  ...            0         0
186     Tim Maciejewski   Union Berlin  ...            0         0
187         Joshua Mees   Union Berlin  ...            0         0

[188 rows x 18 columns]